name: Build SHAGGY26K

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1.5.0
      with:
        haxe-version: '4.2.5'

    - name: Install Haxe Libraries
      run: |
        haxelib install lime
        haxelib install openfl
        haxelib install hxcpp
        haxelib install flixel
        haxelib install flixel-addons
        haxelib install flixel-ui
        haxelib install hscript
        haxelib run lime setup
        haxelib run lime setup flixel

    - name: Build for Windows
      run: haxelib run lime build windows

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SHAGGY26K-Build
        path: export/release/windows/bin
